fix display of GOR in realtime mode
SINTEF/PySilCam pull request #120
Opened 2021-03-10 14:57 UTC by emlynjdavies

GOR value in live raw within the GUI is now the same as in interactive summary

2021-03-10 14:58 UTC, emlynjdavies commented
fixes #114

2021-03-10 14:58 UTC, tankefugl requested changes
[Lintly](https://github.com/grantmcconnaughey/Lintly) has detected code quality issues in this pull request.



<!-- Automatically posted by Lintly -->

2021-03-10 14:58 UTC, tankefugl commented on pysilcam/silcamgui/guicalcs.py
> +                        str(timestamp))
E127: continuation line over-indented for visual indent  <!-- Automatically posted by Lintly -->

2021-03-10 14:58 UTC, tankefugl commented on pysilcam/silcamgui/guicalcs.py
> +
W293: blank line contains whitespace  <!-- Automatically posted by Lintly -->

2021-03-10 14:58 UTC, tankefugl commented on pysilcam/silcamgui/guicalcs.py
> +            except:
E722: do not use bare 'except'  <!-- Automatically posted by Lintly -->

2021-03-10 14:58 UTC, tankefugl commented on pysilcam/oilgas.py
> +        self.vd_gas = (self.vd_gas / np.sum(self.vd_gas)) * volume_concentration_gas  # re-scale the volume distribution to the correct gas concentraiton
E501: line too long (153 > 130 characters)  <!-- Automatically posted by Lintly -->

2021-03-10 14:58 UTC, tankefugl commented on pysilcam/oilgas.py
> +        self.vd_oil = (self.vd_oil / np.sum(self.vd_oil)) * volume_concentration_oil  # re-scale the volume distribution to the correct oil concentraiton
E501: line too long (153 > 130 characters)  <!-- Automatically posted by Lintly -->

2021-03-10 14:58 UTC, tankefugl commented on pysilcam/oilgas.py
> +
W293: blank line contains whitespace  <!-- Automatically posted by Lintly -->

2021-03-10 15:13 UTC, tankefugl submitted a review, later dismissed
[Lintly](https://github.com/grantmcconnaughey/Lintly) has detected code quality issues in this pull request.



<!-- Automatically posted by Lintly -->

2021-03-11 14:14 UTC, WillRNaylor reviewed
Just need to bump the version number.

2021-03-11 14:20 UTC, WillRNaylor approved these changes

2021-03-11 15:31 UTC, merged