51 vimba python emlyndev
SINTEF/PySilCam pull request #134
Opened 2021-04-24 22:00 UTC by emlynjdavies

2021-04-24 22:01 UTC, tankefugl requested changes
[Lintly](https://github.com/grantmcconnaughey/Lintly) has detected code quality issues in this pull request.



<!-- Automatically posted by Lintly -->

2021-04-24 22:01 UTC, tankefugl commented on pysilcam/background.py
> +                    addToQueue(self.real_time_stats, self.proc_image_queue, image_number, timestamp, imc)  # the tuple (i, timestamp, imc) is added to the inputQueue
E501: line too long (165 > 130 characters)  <!-- Automatically posted by Lintly -->

2021-04-24 22:01 UTC, tankefugl commented on pysilcam/background.py
> +                        addToQueue(self.real_time_stats, self.proc_image_queue, 0, timestamp, imc)  # the tuple (i, timestamp, imc) is added to the inputQueue
E501: line too long (158 > 130 characters)  <!-- Automatically posted by Lintly -->

2021-04-24 22:01 UTC, tankefugl commented on pysilcam/background.py
> +import matplotlib.pyplot as plt
F401: 'matplotlib.pyplot as plt' imported but unused  <!-- Automatically posted by Lintly -->

2021-04-24 22:01 UTC, tankefugl commented on pysilcam/background.py
> +import os
F401: 'os' imported but unused  <!-- Automatically posted by Lintly -->

2021-04-24 22:01 UTC, tankefugl commented on pysilcam/acquisition.py
> +MyManager.register('LifoQueue', LifoQueue)
W292: no newline at end of file  <!-- Automatically posted by Lintly -->

2021-04-24 22:01 UTC, tankefugl commented on pysilcam/acquisition.py
> +            except:
E722: do not use bare 'except'  <!-- Automatically posted by Lintly -->

2021-04-24 22:01 UTC, tankefugl commented on pysilcam/acquisition.py
> +        except:
E722: do not use bare 'except'  <!-- Automatically posted by Lintly -->

2021-04-24 22:01 UTC, tankefugl commented on pysilcam/acquisition.py
> +            cam.queue_frame(frame)
F821: undefined name 'cam'  <!-- Automatically posted by Lintly -->

2021-04-24 22:01 UTC, tankefugl commented on pysilcam/acquisition.py
> +            except:
E722: do not use bare 'except'  <!-- Automatically posted by Lintly -->

2021-04-24 22:01 UTC, tankefugl commented on pysilcam/acquisition.py
> +                        'vd_oil': 0,
E127: continuation line over-indented for visual indent  <!-- Automatically posted by Lintly -->

2021-04-24 22:01 UTC, tankefugl commented on pysilcam/acquisition.py
> +                except:
E722: do not use bare 'except'  <!-- Automatically posted by Lintly -->

2021-04-24 22:01 UTC, tankefugl commented on pysilcam/acquisition.py
> +                    except:
E722: do not use bare 'except'  <!-- Automatically posted by Lintly -->

2021-04-24 22:01 UTC, tankefugl commented on pysilcam/acquisition.py
> +                        np.save(fh, img, allow_pickle = False)
E251: unexpected spaces around keyword / parameter equals  <!-- Automatically posted by Lintly -->

2021-04-24 22:01 UTC, tankefugl commented on pysilcam/acquisition.py
> +                        np.save(fh, img, allow_pickle = False)
E251: unexpected spaces around keyword / parameter equals  <!-- Automatically posted by Lintly -->

2021-04-24 22:01 UTC, tankefugl commented on pysilcam/acquisition.py
> +            except:
E722: do not use bare 'except'  <!-- Automatically posted by Lintly -->

2021-04-24 22:01 UTC, tankefugl commented on pysilcam/acquisition.py
> +            if datapath != None:
E711: comparison to None should be 'if cond is not None:'  <!-- Automatically posted by Lintly -->

2021-04-24 22:01 UTC, tankefugl commented on pysilcam/acquisition.py
> +
W293: blank line contains whitespace  <!-- Automatically posted by Lintly -->

2021-04-24 22:01 UTC, tankefugl commented on pysilcam/acquisition.py
> +    #Load the raw image from disc depending on filetype
E265: block comment should start with '# '  <!-- Automatically posted by Lintly -->

2021-04-24 22:01 UTC, tankefugl commented on pysilcam/acquisition.py
> +            except AttributeError:  # if there is an element of the camera config that is not compatible, then continue to the next
E501: line too long (131 > 130 characters)  <!-- Automatically posted by Lintly -->

2021-04-24 22:01 UTC, tankefugl commented on pysilcam/__main__.py
> +def silcam_process(config_filename, datapath, multiProcess=True, realtime=False,
C901: 'silcam_process' is too complex (12)  <!-- Automatically posted by Lintly -->

2021-04-24 22:08 UTC, tankefugl requested changes
[Lintly](https://github.com/grantmcconnaughey/Lintly) has detected code quality issues in this pull request.



<!-- Automatically posted by Lintly -->

2021-04-24 22:08 UTC, tankefugl commented on pysilcam/background.py
> +                    addToQueue(self.real_time_stats, self.proc_image_queue, image_number, timestamp, imc)  # the tuple (i, timestamp, imc) is added to the inputQueue
E501: line too long (165 > 130 characters)  <!-- Automatically posted by Lintly -->

2021-04-24 22:08 UTC, tankefugl commented on pysilcam/background.py
> +                        addToQueue(self.real_time_stats, self.proc_image_queue, 0, timestamp, imc)  # the tuple (i, timestamp, imc) is added to the inputQueue
E501: line too long (158 > 130 characters)  <!-- Automatically posted by Lintly -->

2021-04-24 22:08 UTC, tankefugl commented on pysilcam/background.py
> +import matplotlib.pyplot as plt
F401: 'matplotlib.pyplot as plt' imported but unused  <!-- Automatically posted by Lintly -->

2021-04-24 22:08 UTC, tankefugl commented on pysilcam/background.py
> +import os
F401: 'os' imported but unused  <!-- Automatically posted by Lintly -->

2021-04-24 22:08 UTC, tankefugl commented on pysilcam/acquisition.py
> +MyManager.register('LifoQueue', LifoQueue)
W292: no newline at end of file  <!-- Automatically posted by Lintly -->

2021-04-24 22:08 UTC, tankefugl commented on pysilcam/acquisition.py
> +            except:
E722: do not use bare 'except'  <!-- Automatically posted by Lintly -->

2021-04-24 22:08 UTC, tankefugl commented on pysilcam/acquisition.py
> +        except:
E722: do not use bare 'except'  <!-- Automatically posted by Lintly -->

2021-04-24 22:08 UTC, tankefugl commented on pysilcam/acquisition.py
> +            cam.queue_frame(frame)
F821: undefined name 'cam'  <!-- Automatically posted by Lintly -->

2021-04-24 22:08 UTC, tankefugl commented on pysilcam/acquisition.py
> +            except:
E722: do not use bare 'except'  <!-- Automatically posted by Lintly -->

2021-04-24 22:08 UTC, tankefugl commented on pysilcam/acquisition.py
> +                        'vd_oil': 0,
E127: continuation line over-indented for visual indent  <!-- Automatically posted by Lintly -->

2021-04-24 22:08 UTC, tankefugl commented on pysilcam/acquisition.py
> +                except:
E722: do not use bare 'except'  <!-- Automatically posted by Lintly -->

2021-04-24 22:08 UTC, tankefugl commented on pysilcam/acquisition.py
> +                    except:
E722: do not use bare 'except'  <!-- Automatically posted by Lintly -->

2021-04-24 22:08 UTC, tankefugl commented on pysilcam/acquisition.py
> +                        np.save(fh, img, allow_pickle = False)
E251: unexpected spaces around keyword / parameter equals  <!-- Automatically posted by Lintly -->

2021-04-24 22:08 UTC, tankefugl commented on pysilcam/acquisition.py
> +                        np.save(fh, img, allow_pickle = False)
E251: unexpected spaces around keyword / parameter equals  <!-- Automatically posted by Lintly -->

2021-04-24 22:08 UTC, tankefugl commented on pysilcam/acquisition.py
> +            except:
E722: do not use bare 'except'  <!-- Automatically posted by Lintly -->

2021-04-24 22:08 UTC, tankefugl commented on pysilcam/acquisition.py
> +            if datapath != None:
E711: comparison to None should be 'if cond is not None:'  <!-- Automatically posted by Lintly -->

2021-04-24 22:08 UTC, tankefugl commented on pysilcam/acquisition.py
> +
W293: blank line contains whitespace  <!-- Automatically posted by Lintly -->

2021-04-24 22:08 UTC, tankefugl commented on pysilcam/acquisition.py
> +    #Load the raw image from disc depending on filetype
E265: block comment should start with '# '  <!-- Automatically posted by Lintly -->

2021-04-24 22:08 UTC, tankefugl commented on pysilcam/acquisition.py
> +            except AttributeError:  # if there is an element of the camera config that is not compatible, then continue to the next
E501: line too long (131 > 130 characters)  <!-- Automatically posted by Lintly -->

2021-04-24 22:08 UTC, tankefugl commented on pysilcam/__main__.py
> +def silcam_process(config_filename, datapath, multiProcess=True, realtime=False,
C901: 'silcam_process' is too complex (12)  <!-- Automatically posted by Lintly -->

2021-04-25 07:34 UTC, tankefugl requested changes
[Lintly](https://github.com/grantmcconnaughey/Lintly) has detected code quality issues in this pull request.



<!-- Automatically posted by Lintly -->

2021-04-25 07:34 UTC, tankefugl commented on pysilcam/background.py
> +                    addToQueue(self.real_time_stats, self.proc_image_queue, image_number, timestamp, imc)  # the tuple (i, timestamp, imc) is added to the inputQueue
E501: line too long (165 > 130 characters)  <!-- Automatically posted by Lintly -->

2021-04-25 07:34 UTC, tankefugl commented on pysilcam/background.py
> +                        addToQueue(self.real_time_stats, self.proc_image_queue, 0, timestamp, imc)  # the tuple (i, timestamp, imc) is added to the inputQueue
E501: line too long (158 > 130 characters)  <!-- Automatically posted by Lintly -->

2021-04-25 07:34 UTC, tankefugl commented on pysilcam/background.py
> +import matplotlib.pyplot as plt
F401: 'matplotlib.pyplot as plt' imported but unused  <!-- Automatically posted by Lintly -->

2021-04-25 07:34 UTC, tankefugl commented on pysilcam/background.py
> +import os
F401: 'os' imported but unused  <!-- Automatically posted by Lintly -->

2021-04-25 07:34 UTC, tankefugl commented on pysilcam/acquisition.py
> +MyManager.register('LifoQueue', LifoQueue)
W292: no newline at end of file  <!-- Automatically posted by Lintly -->

2021-04-25 07:34 UTC, tankefugl commented on pysilcam/acquisition.py
> +            except:
E722: do not use bare 'except'  <!-- Automatically posted by Lintly -->

2021-04-25 07:34 UTC, tankefugl commented on pysilcam/acquisition.py
> +        except:
E722: do not use bare 'except'  <!-- Automatically posted by Lintly -->

2021-04-25 07:34 UTC, tankefugl commented on pysilcam/acquisition.py
> +            cam.queue_frame(frame)
F821: undefined name 'cam'  <!-- Automatically posted by Lintly -->

2021-04-25 07:34 UTC, tankefugl commented on pysilcam/acquisition.py
> +            except:
E722: do not use bare 'except'  <!-- Automatically posted by Lintly -->

2021-04-25 07:34 UTC, tankefugl commented on pysilcam/acquisition.py
> +                        'vd_oil': 0,
E127: continuation line over-indented for visual indent  <!-- Automatically posted by Lintly -->

2021-04-25 07:34 UTC, tankefugl commented on pysilcam/acquisition.py
> +                except:
E722: do not use bare 'except'  <!-- Automatically posted by Lintly -->

2021-04-25 07:34 UTC, tankefugl commented on pysilcam/acquisition.py
> +                    except:
E722: do not use bare 'except'  <!-- Automatically posted by Lintly -->

2021-04-25 07:34 UTC, tankefugl commented on pysilcam/acquisition.py
> +                        np.save(fh, img, allow_pickle = False)
E251: unexpected spaces around keyword / parameter equals  <!-- Automatically posted by Lintly -->

2021-04-25 07:34 UTC, tankefugl commented on pysilcam/acquisition.py
> +                        np.save(fh, img, allow_pickle = False)
E251: unexpected spaces around keyword / parameter equals  <!-- Automatically posted by Lintly -->

2021-04-25 07:34 UTC, tankefugl commented on pysilcam/acquisition.py
> +            except:
E722: do not use bare 'except'  <!-- Automatically posted by Lintly -->

2021-04-25 07:34 UTC, tankefugl commented on pysilcam/acquisition.py
> +            if datapath != None:
E711: comparison to None should be 'if cond is not None:'  <!-- Automatically posted by Lintly -->

2021-04-25 07:34 UTC, tankefugl commented on pysilcam/acquisition.py
> +
W293: blank line contains whitespace  <!-- Automatically posted by Lintly -->

2021-04-25 07:34 UTC, tankefugl commented on pysilcam/acquisition.py
> +    #Load the raw image from disc depending on filetype
E265: block comment should start with '# '  <!-- Automatically posted by Lintly -->

2021-04-25 07:34 UTC, tankefugl commented on pysilcam/acquisition.py
> +            except AttributeError:  # if there is an element of the camera config that is not compatible, then continue to the next
E501: line too long (131 > 130 characters)  <!-- Automatically posted by Lintly -->

2021-04-25 07:34 UTC, tankefugl commented on pysilcam/__main__.py
> +def silcam_process(config_filename, datapath, multiProcess=True, realtime=False,
C901: 'silcam_process' is too complex (12)  <!-- Automatically posted by Lintly -->

2021-04-25 07:40 UTC, closed without merging

2021-04-25 07:40 UTC, emlynjdavies commented
only opened for testing