Trim stats in interractive summary
SINTEF/PySilCam pull request #45
Opened 2020-09-22 11:24 UTC by emlynjdavies

quick adding of the 'trim stats' tool into the summary GUI to help with faster data exploring without reloading large files all the time.

2020-09-22 11:24 UTC, tankefugl requested changes
[Lintly](https://github.com/grantmcconnaughey/Lintly) has detected code quality issues in this pull request.



<!-- Automatically posted by Lintly -->

2020-09-22 11:24 UTC, tankefugl commented on pysilcam/silcamgui/interactive_summary.py
> +    def save_trimmed_stats(self):
E303: too many blank lines (2)  <!-- Automatically posted by Lintly -->

2020-09-22 11:24 UTC, tankefugl commented on pysilcam/silcamgui/interactive_summary.py
> +        if len(self.stats)==0:
E225: missing whitespace around operator  <!-- Automatically posted by Lintly -->

2020-09-22 14:02 UTC, tankefugl approved these changes
No linting violations have been found in this PR.



<!-- Automatically posted by Lintly -->

2020-10-09 07:37 UTC, bjarnekvae approved these changes

2020-10-09 10:16 UTC, tankefugl approved these changes
No linting violations have been found in this PR.



<!-- Automatically posted by Lintly -->

2020-10-09 10:18 UTC, tankefugl approved these changes
No linting violations have been found in this PR.



<!-- Automatically posted by Lintly -->

2020-10-09 11:03 UTC, merged