Update config.py
SINTEF/PySilCam pull request #56
Opened 2020-10-08 13:11 UTC by emlynjdavies

2020-10-08 13:12 UTC, tankefugl submitted a review, later dismissed
No linting violations have been found in this PR.



<!-- Automatically posted by Lintly -->

2020-10-08 14:46 UTC, tankefugl requested changes
[Lintly](https://github.com/grantmcconnaughey/Lintly) has detected code quality issues in this pull request.



<!-- Automatically posted by Lintly -->

2020-10-08 14:46 UTC, tankefugl commented on pysilcam/pathadjust.py
> +class PathLength():
E302: expected 2 blank lines, found 1  <!-- Automatically posted by Lintly -->

2020-10-08 14:46 UTC, tankefugl commented on pysilcam/pathadjust.py
> +        readout1 = self.ser.read(1000)
F841: local variable 'readout1' is assigned to but never used  <!-- Automatically posted by Lintly -->

2020-10-08 14:46 UTC, tankefugl commented on pysilcam/pathadjust.py
> +        readout1 = self.ser.read(1000)
F841: local variable 'readout1' is assigned to but never used  <!-- Automatically posted by Lintly -->

2020-10-08 14:46 UTC, tankefugl commented on pysilcam/pathadjust.py
> +        logger.info('actuator port closed!')
W292: no newline at end of file  <!-- Automatically posted by Lintly -->

2020-10-08 14:53 UTC, tankefugl approved these changes
No linting violations have been found in this PR.



<!-- Automatically posted by Lintly -->

2020-10-08 19:26 UTC, emlynjdavies commented
for silcams with adjustable path lengths, this is updated via serial communication using the PathLength class, and vary rarely tested because this hardware needs to be connected. This is done for the first time within  pysilcam/config.py (because the path length is an important configuration parameter for correctly scaling concentrations).

There was a bug here, due to circular imports, where the PathLength class was in the pysilcam.oilgas module - but pysilcam.oilgas also imported pysilcam-config. This PR moves the PathLength class code from pysilcam.oilgas into pysilcam.pathadjust

2020-10-09 07:33 UTC, bjarnekvae approved these changes

2020-10-09 10:16 UTC, merged