Particle tracker
SINTEF/PySilCam pull request #57
Opened 2020-10-09 10:52 UTC by emlynjdavies

New module for tracking particles in datasets where they can be followed.

command line useage:
        silcam-track process <configfile> <datapath> [--offset=<offset>]
        silcam-track post-process <tracksfile>
        silcam-track plotting <tracksfile> [--gif=<outputdir>] [<rawdatapath>] [--boxplot]

2020-10-09 11:34 UTC, tankefugl requested changes
[Lintly](https://github.com/grantmcconnaughey/Lintly) has detected code quality issues in this pull request.



<!-- Automatically posted by Lintly -->

2020-10-09 11:34 UTC, tankefugl commented on pysilcam/fakepymba.py
> +        img0[:,:,0] = img_mono
E231: missing whitespace after ','  <!-- Automatically posted by Lintly -->

2020-10-09 11:34 UTC, tankefugl commented on pysilcam/fakepymba.py
> +        img0[:,:,0] = img_mono
E231: missing whitespace after ','  <!-- Automatically posted by Lintly -->

2020-10-09 11:34 UTC, tankefugl commented on pysilcam/silcamgui/guicalcs.py
> +            if f.endswith('.silc') or f.endswith('.bmp') or f.endswith('.silc_mono')]
E128: continuation line under-indented for visual indent  <!-- Automatically posted by Lintly -->

2020-10-09 11:34 UTC, tankefugl commented on pysilcam/tests/test_tracking.py
> +@unittest.skipIf((ROOTPATH is None),
E302: expected 2 blank lines, found 0  <!-- Automatically posted by Lintly -->

2020-10-09 11:34 UTC, tankefugl commented on pysilcam/tests/test_tracking.py
> +                                        settings.PostProcess.pix_size,
E128: continuation line under-indented for visual indent  <!-- Automatically posted by Lintly -->

2020-10-09 11:34 UTC, tankefugl commented on pysilcam/tests/test_tracking.py
> +                                        track_length_limit=settings.Tracking.track_length_limit)
E128: continuation line under-indented for visual indent  <!-- Automatically posted by Lintly -->

2020-10-09 11:34 UTC, tankefugl commented on pysilcam/tracking/silcamtracker.py
> +                img1 = np.copy(img2)
F821: undefined name 'img2'  <!-- Automatically posted by Lintly -->

2020-10-09 11:34 UTC, tankefugl commented on pysilcam/tracking/silcamtracker.py
> +                t1 = pd.to_datetime(str(np.copy(t2)))
F821: undefined name 't2'  <!-- Automatically posted by Lintly -->

2020-10-09 11:34 UTC, tankefugl commented on pysilcam/tracking/silcamtracker.py
> +            except:
E722: do not use bare 'except'  <!-- Automatically posted by Lintly -->

2020-10-09 11:34 UTC, tankefugl commented on pysilcam/tracking/silcamtracker.py
> +def get_vect(img1, img2, PIX_SIZE, MIN_LENGTH, GOOD_FIT, thresh=0.98,
C901: 'get_vect' is too complex (12)  <!-- Automatically posted by Lintly -->

2020-10-09 11:34 UTC, tankefugl commented on pysilcam/tracking/silcamtracker.py
> +    if not max_starts is None:
E714: test for object identity should be 'is not'  <!-- Automatically posted by Lintly -->

2020-10-09 11:34 UTC, tankefugl commented on pysilcam/tracking/track.py
> +from pysilcam.tracking.silcamtracker import *
F403: 'from pysilcam.tracking.silcamtracker import *' used; unable to detect undefined names  <!-- Automatically posted by Lintly -->

2020-10-09 11:34 UTC, tankefugl commented on pysilcam/tracking/track.py
> +    dataset_name = os.path.split(datapath)[1]
F405: 'os' may be undefined, or defined from star imports: pysilcam.tracking.silcamtracker  <!-- Automatically posted by Lintly -->

2020-10-09 11:34 UTC, tankefugl commented on pysilcam/tracking/track.py
> +    outputpath = os.path.join(datapath, ('../output_' + dataset_name))
F405: 'os' may be undefined, or defined from star imports: pysilcam.tracking.silcamtracker  <!-- Automatically posted by Lintly -->

2020-10-09 11:34 UTC, tankefugl commented on pysilcam/tracking/track.py
> +    os.makedirs(outputpath, exist_ok=True)
F405: 'os' may be undefined, or defined from star imports: pysilcam.tracking.silcamtracker  <!-- Automatically posted by Lintly -->

2020-10-09 11:34 UTC, tankefugl commented on pysilcam/tracking/track.py
> +    figurename = os.path.join(figurename + '.png')
F405: 'os' may be undefined, or defined from star imports: pysilcam.tracking.silcamtracker  <!-- Automatically posted by Lintly -->

2020-10-09 11:34 UTC, tankefugl commented on pysilcam/tracking/track.py
> +    hits = glob.glob(os.path.join(rawdatapath, searchfilename + '*'))
F405: 'os' may be undefined, or defined from star imports: pysilcam.tracking.silcamtracker  <!-- Automatically posted by Lintly -->

2020-10-09 11:34 UTC, tankefugl commented on pysilcam/tracking/track.py
> +    im = silcam_load(imagename)
F405: 'silcam_load' may be undefined, or defined from star imports: pysilcam.tracking.silcamtracker  <!-- Automatically posted by Lintly -->

2020-10-09 11:34 UTC, tankefugl commented on pysilcam/tracking/track.py
> +    os.makedirs(outputdir, exist_ok=True)
F405: 'os' may be undefined, or defined from star imports: pysilcam.tracking.silcamtracker  <!-- Automatically posted by Lintly -->

2020-10-09 11:34 UTC, tankefugl commented on pysilcam/tracking/track.py
> +        except:
E722: do not use bare 'except'  <!-- Automatically posted by Lintly -->

2020-10-09 11:34 UTC, tankefugl commented on pysilcam/tracking/track.py
> +        print('saving', os.path.join(outputdir, name + '-tr.png'))
F405: 'os' may be undefined, or defined from star imports: pysilcam.tracking.silcamtracker  <!-- Automatically posted by Lintly -->

2020-10-09 11:34 UTC, tankefugl commented on pysilcam/tracking/track.py
> +        plt.savefig(os.path.join(outputdir, name + '-tr.png'), dpi=300, bbox_inches='tight')
F405: 'os' may be undefined, or defined from star imports: pysilcam.tracking.silcamtracker  <!-- Automatically posted by Lintly -->

2020-10-09 11:34 UTC, tankefugl commented on pysilcam/tracking/track.py
> +    with h5py.File(h5filename) as f:
F405: 'h5py' may be undefined, or defined from star imports: pysilcam.tracking.silcamtracker  <!-- Automatically posted by Lintly -->

2020-10-09 11:34 UTC, tankefugl commented on pysilcam/tracking/track.py
> +        groups = [obj for obj in objs if isinstance(f[obj], h5py.Group)]
F405: 'h5py' may be undefined, or defined from star imports: pysilcam.tracking.silcamtracker  <!-- Automatically posted by Lintly -->

2020-10-09 11:34 UTC, tankefugl commented on pysilcam/tracking/track.py
> +    files = [os.path.join(datapath, f) for f in sorted(os.listdir(datapath)) if
F405: 'os' may be undefined, or defined from star imports: pysilcam.tracking.silcamtracker  <!-- Automatically posted by Lintly -->

2020-10-09 11:34 UTC, tankefugl commented on pysilcam/tracking/track.py
> +    files = [os.path.join(datapath, f) for f in sorted(os.listdir(datapath)) if
F405: 'os' may be undefined, or defined from star imports: pysilcam.tracking.silcamtracker  <!-- Automatically posted by Lintly -->

2020-10-09 11:34 UTC, tankefugl commented on pysilcam/tracking/track.py
> +    except:
E722: do not use bare 'except'  <!-- Automatically posted by Lintly -->

2020-10-09 11:34 UTC, tankefugl commented on pysilcam/tracking/track.py
> +        except:
E722: do not use bare 'except'  <!-- Automatically posted by Lintly -->

2020-10-09 11:34 UTC, tankefugl commented on pysilcam/tracking/track.py
> +            except:
E722: do not use bare 'except'  <!-- Automatically posted by Lintly -->

2020-10-09 11:34 UTC, tankefugl commented on pysilcam/tracking/track.py
> +    tracks = post_process(data, PIX_SIZE,
F405: 'post_process' may be undefined, or defined from star imports: pysilcam.tracking.silcamtracker  <!-- Automatically posted by Lintly -->

2020-10-09 11:34 UTC, tankefugl commented on pysilcam/tracking/track.py
> +    sctr = Tracker()
F405: 'Tracker' may be undefined, or defined from star imports: pysilcam.tracking.silcamtracker  <!-- Automatically posted by Lintly -->

2020-10-09 11:34 UTC, tankefugl commented on pysilcam/tracking/track.py
> +    dataset_name = os.path.split(datapath)[-1] + '-TRACKS'
F405: 'os' may be undefined, or defined from star imports: pysilcam.tracking.silcamtracker  <!-- Automatically posted by Lintly -->

2020-10-09 11:34 UTC, tankefugl commented on pysilcam/tracking/track.py
> +    sctr.DATAFILE = os.path.join(settings.General.datafile, dataset_name)
F405: 'os' may be undefined, or defined from star imports: pysilcam.tracking.silcamtracker  <!-- Automatically posted by Lintly -->

2020-10-09 11:34 UTC, tankefugl commented on pysilcam/tracking/track.py
> +    os.makedirs(settings.General.datafile, exist_ok=True)
F405: 'os' may be undefined, or defined from star imports: pysilcam.tracking.silcamtracker  <!-- Automatically posted by Lintly -->

2020-10-09 11:34 UTC, tankefugl commented on pysilcam/tracking/track.py
> +    with h5py.File(sctr.DATAFILE + '.h5', "a") as HDF5File:
F405: 'h5py' may be undefined, or defined from star imports: pysilcam.tracking.silcamtracker  <!-- Automatically posted by Lintly -->

2020-10-09 11:34 UTC, tankefugl commented on pysilcam/tracking/track.py
> +    h5filedir = os.path.split(tracksfile)[0]
F405: 'os' may be undefined, or defined from star imports: pysilcam.tracking.silcamtracker  <!-- Automatically posted by Lintly -->

2020-10-09 11:34 UTC, tankefugl commented on pysilcam/tracking/track.py
> +    h5file_list = glob.glob(os.path.join(h5filedir, '*-TRACKS.h5'))
F405: 'os' may be undefined, or defined from star imports: pysilcam.tracking.silcamtracker  <!-- Automatically posted by Lintly -->

2020-10-09 11:34 UTC, tankefugl commented on pysilcam/tracking/track.py
> +    dataset_names = [os.path.split(k)[-1].replace('-TRACKS.h5', '') for k in h5file_list]
F405: 'os' may be undefined, or defined from star imports: pysilcam.tracking.silcamtracker  <!-- Automatically posted by Lintly -->

2020-10-09 11:34 UTC, tankefugl commented on pysilcam/tracking/track.py
> +        unfiltered_tracks = extract_continuous_tracks(data)
F405: 'extract_continuous_tracks' may be undefined, or defined from star imports: pysilcam.tracking.silcamtracker  <!-- Automatically posted by Lintly -->

2020-10-09 11:34 UTC, tankefugl commented on pysilcam/tracking/track.py
> +                unfiltered_tracks = extract_continuous_tracks(data)
F405: 'extract_continuous_tracks' may be undefined, or defined from star imports: pysilcam.tracking.silcamtracker  <!-- Automatically posted by Lintly -->

2020-10-09 12:05 UTC, tankefugl requested changes
[Lintly](https://github.com/grantmcconnaughey/Lintly) has detected code quality issues in this pull request.



<!-- Automatically posted by Lintly -->

2020-10-09 12:05 UTC, tankefugl commented on pysilcam/fakepymba.py
> +        img0[:,:, 0] = img_mono
E231: missing whitespace after ','  <!-- Automatically posted by Lintly -->

2020-10-09 12:05 UTC, tankefugl commented on pysilcam/silcamgui/guicalcs.py
> +            if f.endswith('.silc') or f.endswith('.bmp') or f.endswith('.silc_mono')]
E128: continuation line under-indented for visual indent  <!-- Automatically posted by Lintly -->

2020-10-09 12:05 UTC, tankefugl commented on pysilcam/tracking/silcamtracker.py
> +                img1 = np.copy(img2)
F821: undefined name 'img2'  <!-- Automatically posted by Lintly -->

2020-10-09 12:05 UTC, tankefugl commented on pysilcam/tracking/silcamtracker.py
> +                t1 = pd.to_datetime(str(np.copy(t2)))
F821: undefined name 't2'  <!-- Automatically posted by Lintly -->

2020-10-09 12:05 UTC, tankefugl commented on pysilcam/tracking/silcamtracker.py
> +            except:
E722: do not use bare 'except'  <!-- Automatically posted by Lintly -->

2020-10-09 12:05 UTC, tankefugl commented on pysilcam/tracking/silcamtracker.py
> +def get_vect(img1, img2, PIX_SIZE, MIN_LENGTH, GOOD_FIT, thresh=0.98,
C901: 'get_vect' is too complex (12)  <!-- Automatically posted by Lintly -->

2020-10-09 12:05 UTC, tankefugl commented on pysilcam/tracking/silcamtracker.py
> +    if not max_starts is None:
E714: test for object identity should be 'is not'  <!-- Automatically posted by Lintly -->

2020-10-09 12:05 UTC, tankefugl commented on pysilcam/tracking/track.py
> +        except:
E722: do not use bare 'except'  <!-- Automatically posted by Lintly -->

2020-10-09 12:05 UTC, tankefugl commented on pysilcam/tracking/track.py
> +    except:
E722: do not use bare 'except'  <!-- Automatically posted by Lintly -->

2020-10-09 12:05 UTC, tankefugl commented on pysilcam/tracking/track.py
> +        except:
E722: do not use bare 'except'  <!-- Automatically posted by Lintly -->

2020-10-09 12:05 UTC, tankefugl commented on pysilcam/tracking/track.py
> +            except:
E722: do not use bare 'except'  <!-- Automatically posted by Lintly -->

2020-10-09 12:05 UTC, tankefugl commented on pysilcam/tracking/track.py
> +                          track_length_limit=track_length_limit,
E128: continuation line under-indented for visual indent  <!-- Automatically posted by Lintly -->

2020-10-09 12:05 UTC, tankefugl commented on pysilcam/tracking/track.py
> +                          minlength=minlength, maxlength=maxlength)
E128: continuation line under-indented for visual indent  <!-- Automatically posted by Lintly -->

2020-10-09 12:28 UTC, tankefugl requested changes
[Lintly](https://github.com/grantmcconnaughey/Lintly) has detected code quality issues in this pull request.



<!-- Automatically posted by Lintly -->

2020-10-09 12:28 UTC, tankefugl commented on pysilcam/silcamgui/guicalcs.py
> +            or f.endswith('.silc_mono')]
E128: continuation line under-indented for visual indent  <!-- Automatically posted by Lintly -->

2020-10-09 12:28 UTC, tankefugl commented on pysilcam/tracking/silcamtracker.py
> +            except: # pylint: disable=broad-except
E722: do not use bare 'except'  <!-- Automatically posted by Lintly -->

2020-10-09 12:28 UTC, tankefugl commented on pysilcam/tracking/silcamtracker.py
> +            except: # pylint: disable=broad-except
E261: at least two spaces before inline comment  <!-- Automatically posted by Lintly -->

2020-10-09 12:28 UTC, tankefugl commented on pysilcam/tracking/silcamtracker.py
> +def get_vect(img1, img2, PIX_SIZE, MIN_LENGTH, GOOD_FIT, thresh=0.98,
C901: 'get_vect' is too complex (12)  <!-- Automatically posted by Lintly -->

2020-10-09 12:28 UTC, tankefugl commented on pysilcam/tracking/silcamtracker.py
> +    if not max_starts is None:
E714: test for object identity should be 'is not'  <!-- Automatically posted by Lintly -->

2020-10-09 12:28 UTC, tankefugl commented on pysilcam/tracking/track.py
> +from scipy import interpolate
F401: 'scipy.interpolate' imported but unused  <!-- Automatically posted by Lintly -->

2020-10-09 12:28 UTC, tankefugl commented on pysilcam/tracking/track.py
> +        except:
E722: do not use bare 'except'  <!-- Automatically posted by Lintly -->

2020-10-09 12:57 UTC, tankefugl requested changes
[Lintly](https://github.com/grantmcconnaughey/Lintly) has detected code quality issues in this pull request.



<!-- Automatically posted by Lintly -->

2020-10-09 12:57 UTC, tankefugl commented on pysilcam/silcamgui/guicalcs.py
> +    except:  # pylint: disable=broad-except
E722: do not use bare 'except'  <!-- Automatically posted by Lintly -->

2020-10-09 12:57 UTC, tankefugl commented on pysilcam/tracking/silcamtracker.py
> +                img1 = np.copy(img2)
F821: undefined name 'img2'  <!-- Automatically posted by Lintly -->

2020-10-09 12:57 UTC, tankefugl commented on pysilcam/tracking/silcamtracker.py
> +                t1 = pd.to_datetime(str(np.copy(t2)))
F821: undefined name 't2'  <!-- Automatically posted by Lintly -->

2020-10-09 12:57 UTC, tankefugl commented on pysilcam/tracking/silcamtracker.py
> +            except:  # pylint: disable=broad-except
E722: do not use bare 'except'  <!-- Automatically posted by Lintly -->

2020-10-09 12:57 UTC, tankefugl commented on pysilcam/tracking/silcamtracker.py
> +def get_vect(img1, img2, PIX_SIZE, MIN_LENGTH, GOOD_FIT, thresh=0.98, ecd_tolerance=0):
C901: 'get_vect' is too complex (12)  <!-- Automatically posted by Lintly -->

2020-10-09 12:57 UTC, tankefugl commented on pysilcam/tracking/track.py
> +        except:
E722: do not use bare 'except'  <!-- Automatically posted by Lintly -->

2020-10-09 13:05 UTC, tankefugl requested changes
[Lintly](https://github.com/grantmcconnaughey/Lintly) has detected code quality issues in this pull request.



<!-- Automatically posted by Lintly -->

2020-10-09 13:05 UTC, tankefugl commented on pysilcam/silcamgui/guicalcs.py
> +    except:  # pylint: disable=bare-except
E722: do not use bare 'except'  <!-- Automatically posted by Lintly -->

2020-10-09 13:05 UTC, tankefugl commented on pysilcam/tracking/silcamtracker.py
> +            except:  # pylint: disable=bare-except
E722: do not use bare 'except'  <!-- Automatically posted by Lintly -->

2020-10-09 13:05 UTC, tankefugl commented on pysilcam/tracking/silcamtracker.py
> +def get_vect(img1, img2, PIX_SIZE, MIN_LENGTH, GOOD_FIT, thresh=0.98, ecd_tolerance=0):
C901: 'get_vect' is too complex (12)  <!-- Automatically posted by Lintly -->

2020-10-09 13:05 UTC, tankefugl commented on pysilcam/tracking/track.py
> +        except:  # pylint: disable=bare-except
E722: do not use bare 'except'  <!-- Automatically posted by Lintly -->

2020-10-09 13:10 UTC, tankefugl requested changes
[Lintly](https://github.com/grantmcconnaughey/Lintly) has detected code quality issues in this pull request.



<!-- Automatically posted by Lintly -->

2020-10-09 13:10 UTC, tankefugl commented on pysilcam/tracking/silcamtracker.py
> +            except:  # pylint: disable=bare-except
E722: do not use bare 'except'  <!-- Automatically posted by Lintly -->

2020-10-09 13:10 UTC, tankefugl commented on pysilcam/tracking/silcamtracker.py
> +def get_vect(img1, img2, PIX_SIZE, MIN_LENGTH, GOOD_FIT, thresh=0.98, ecd_tolerance=0):
C901: 'get_vect' is too complex (12)  <!-- Automatically posted by Lintly -->

2020-10-09 13:10 UTC, tankefugl commented on pysilcam/tracking/track.py
> +        except:  # pylint: disable=bare-except
E722: do not use bare 'except'  <!-- Automatically posted by Lintly -->

2020-10-09 13:13 UTC, tankefugl requested changes
[Lintly](https://github.com/grantmcconnaughey/Lintly) has detected code quality issues in this pull request.



<!-- Automatically posted by Lintly -->

2020-10-09 13:13 UTC, tankefugl commented on pysilcam/tracking/silcamtracker.py
> +            except:
E722: do not use bare 'except'  <!-- Automatically posted by Lintly -->

2020-10-09 13:13 UTC, tankefugl commented on pysilcam/tracking/silcamtracker.py
> +def get_vect(img1, img2, PIX_SIZE, MIN_LENGTH, GOOD_FIT, thresh=0.98, ecd_tolerance=0):
C901: 'get_vect' is too complex (12)  <!-- Automatically posted by Lintly -->

2020-10-09 13:13 UTC, tankefugl commented on pysilcam/tracking/track.py
> +        except:
E722: do not use bare 'except'  <!-- Automatically posted by Lintly -->

2020-10-09 13:19 UTC, tankefugl requested changes
[Lintly](https://github.com/grantmcconnaughey/Lintly) has detected code quality issues in this pull request.



<!-- Automatically posted by Lintly -->

2020-10-09 13:19 UTC, tankefugl commented on pysilcam/tracking/silcamtracker.py
> +            except:
E722: do not use bare 'except'  <!-- Automatically posted by Lintly -->

2020-10-09 13:19 UTC, tankefugl commented on pysilcam/tracking/silcamtracker.py
> +def get_vect(img1, img2, PIX_SIZE, MIN_LENGTH, GOOD_FIT, thresh=0.98, ecd_tolerance=0):
C901: 'get_vect' is too complex (12)  <!-- Automatically posted by Lintly -->

2020-10-09 13:19 UTC, tankefugl commented on pysilcam/tracking/track.py
> +        except:
E722: do not use bare 'except'  <!-- Automatically posted by Lintly -->

2020-10-09 13:20 UTC, tankefugl requested changes
[Lintly](https://github.com/grantmcconnaughey/Lintly) has detected code quality issues in this pull request.



<!-- Automatically posted by Lintly -->

2020-10-09 13:20 UTC, tankefugl commented on pysilcam/tracking/silcamtracker.py
> +            except:
E722: do not use bare 'except'  <!-- Automatically posted by Lintly -->

2020-10-09 13:20 UTC, tankefugl commented on pysilcam/tracking/silcamtracker.py
> +def get_vect(img1, img2, PIX_SIZE, MIN_LENGTH, GOOD_FIT, thresh=0.98, ecd_tolerance=0):
C901: 'get_vect' is too complex (12)  <!-- Automatically posted by Lintly -->

2020-10-09 13:20 UTC, tankefugl commented on pysilcam/tracking/track.py
> +        except:
E722: do not use bare 'except'  <!-- Automatically posted by Lintly -->

2020-10-09 13:29 UTC, tankefugl requested changes
[Lintly](https://github.com/grantmcconnaughey/Lintly) has detected code quality issues in this pull request.



<!-- Automatically posted by Lintly -->

2020-10-09 13:29 UTC, tankefugl commented on pysilcam/tracking/silcamtracker.py
> +            except Exception as error:
F841: local variable 'error' is assigned to but never used  <!-- Automatically posted by Lintly -->

2020-10-09 13:29 UTC, tankefugl commented on pysilcam/tracking/silcamtracker.py
> +def get_vect(img1, img2, PIX_SIZE, MIN_LENGTH, GOOD_FIT, thresh=0.98, ecd_tolerance=0):
C901: 'get_vect' is too complex (12)  <!-- Automatically posted by Lintly -->

2020-10-09 13:29 UTC, tankefugl commented on pysilcam/tracking/track.py
> +        except Exception as error:
F841: local variable 'error' is assigned to but never used  <!-- Automatically posted by Lintly -->

2020-10-09 13:31 UTC, tankefugl requested changes
[Lintly](https://github.com/grantmcconnaughey/Lintly) has detected code quality issues in this pull request.



<!-- Automatically posted by Lintly -->

2020-10-09 13:31 UTC, tankefugl commented on pysilcam/tracking/silcamtracker.py
> +def get_vect(img1, img2, PIX_SIZE, MIN_LENGTH, GOOD_FIT, thresh=0.98, ecd_tolerance=0):
C901: 'get_vect' is too complex (12)  <!-- Automatically posted by Lintly -->

2020-10-09 13:31 UTC, tankefugl commented on pysilcam/tracking/track.py
> +        except Exception as error:
F841: local variable 'error' is assigned to but never used  <!-- Automatically posted by Lintly -->

2020-10-09 14:06 UTC, tankefugl requested changes
[Lintly](https://github.com/grantmcconnaughey/Lintly) has detected code quality issues in this pull request.



<!-- Automatically posted by Lintly -->

2020-10-09 14:06 UTC, tankefugl commented on pysilcam/tracking/silcamtracker.py
> +def get_vect(img1, img2, PIX_SIZE, MIN_LENGTH, GOOD_FIT, thresh=0.98, ecd_tolerance=0):
C901: 'get_vect' is too complex (12)  <!-- Automatically posted by Lintly -->

2020-10-12 09:40 UTC, tankefugl submitted a review, later dismissed
No linting violations have been found in this PR.



<!-- Automatically posted by Lintly -->

2020-10-12 10:10 UTC, tankefugl requested changes
[Lintly](https://github.com/grantmcconnaughey/Lintly) has detected code quality issues in this pull request.



<!-- Automatically posted by Lintly -->

2020-10-12 10:10 UTC, tankefugl commented on pysilcam/tracking/silcamtracker.py
> +    cross_correlation = match_template(search_roi>0, roi)
E225: missing whitespace around operator  <!-- Automatically posted by Lintly -->

2020-10-12 10:10 UTC, tankefugl commented on pysilcam/tracking/silcamtracker.py
> +        #x_ += ((bbox[3] - bbox[1]) / 2)
E265: block comment should start with '# '  <!-- Automatically posted by Lintly -->

2020-10-12 10:10 UTC, tankefugl commented on pysilcam/tracking/silcamtracker.py
> +        #y_ += ((bbox[2] - bbox[0]) / 2)
E265: block comment should start with '# '  <!-- Automatically posted by Lintly -->

2020-10-12 10:10 UTC, tankefugl commented on pysilcam/tracking/silcamtracker.py
> +        #idx = iml2[int(y_ + search_box[0]), int(x_ + search_box[1])]
E265: block comment should start with '# '  <!-- Automatically posted by Lintly -->

2020-10-12 10:11 UTC, tankefugl requested changes
[Lintly](https://github.com/grantmcconnaughey/Lintly) has detected code quality issues in this pull request.



<!-- Automatically posted by Lintly -->

2020-10-12 10:11 UTC, tankefugl commented on pysilcam/tracking/silcamtracker.py
> +        #x_ += ((bbox[3] - bbox[1]) / 2)
E265: block comment should start with '# '  <!-- Automatically posted by Lintly -->

2020-10-12 10:11 UTC, tankefugl commented on pysilcam/tracking/silcamtracker.py
> +        #y_ += ((bbox[2] - bbox[0]) / 2)
E265: block comment should start with '# '  <!-- Automatically posted by Lintly -->

2020-10-12 10:11 UTC, tankefugl commented on pysilcam/tracking/silcamtracker.py
> +        #idx = iml2[int(y_ + search_box[0]), int(x_ + search_box[1])]
E265: block comment should start with '# '  <!-- Automatically posted by Lintly -->

2020-10-12 14:00 UTC, tankefugl approved these changes
No linting violations have been found in this PR.



<!-- Automatically posted by Lintly -->

2020-10-12 14:15 UTC, tankefugl approved these changes
No linting violations have been found in this PR.



<!-- Automatically posted by Lintly -->

2020-11-09 15:39 UTC, closed without merging

2020-11-09 15:39 UTC, emlynjdavies commented
use branch: dev-tracker instead