inplace set to False in extract_nth functions git push
SINTEF/PySilCam pull request #59
Opened 2020-10-13 11:26 UTC by emlynjdavies

fixes issue #58

2020-10-13 11:27 UTC, tankefugl approved these changes
No linting violations have been found in this PR.



<!-- Automatically posted by Lintly -->

2020-10-27 09:24 UTC, tankefugl requested changes
[Lintly](https://github.com/grantmcconnaughey/Lintly) has detected code quality issues in this pull request.



<!-- Automatically posted by Lintly -->

2020-10-27 09:24 UTC, tankefugl commented on tfl_tools/silcam_classifier_database_builder.py
> +        stats_ = scpp.extract_nth_largest(stats,n=index)
E231: missing whitespace after ','  <!-- Automatically posted by Lintly -->

2020-10-27 09:26 UTC, nepstad approved these changes

2020-10-27 09:31 UTC, nepstad submitted a review, later dismissed

2020-10-27 09:37 UTC, tankefugl submitted a review, later dismissed
[Lintly](https://github.com/grantmcconnaughey/Lintly) has detected code quality issues in this pull request.



<!-- Automatically posted by Lintly -->

2020-10-27 09:37 UTC, tankefugl commented on tfl_tools/silcam_classifier_database_builder.py
> +        stats_ = scpp.extract_nth_largest(stats, n = index)
E251: unexpected spaces around keyword / parameter equals  <!-- Automatically posted by Lintly -->

2020-10-27 09:37 UTC, tankefugl commented on tfl_tools/silcam_classifier_database_builder.py
> +        stats_ = scpp.extract_nth_largest(stats, n = index)
E251: unexpected spaces around keyword / parameter equals  <!-- Automatically posted by Lintly -->

2020-10-27 09:51 UTC, nepstad approved these changes

2020-10-27 10:07 UTC, WillRNaylor approved these changes
Code looks good.

2020-10-27 10:09 UTC, merged