add speed test
SINTEF/PySilCam pull request #65
Opened 2020-10-29 12:25 UTC by emlynjdavies

basic timing of silcam_process without multiprocessing with assertion based on a reasonable computer.

2020-10-29 12:26 UTC, tankefugl requested changes
[Lintly](https://github.com/grantmcconnaughey/Lintly) has detected code quality issues in this pull request.



<!-- Automatically posted by Lintly -->

2020-10-29 12:26 UTC, tankefugl commented on pysilcam/tests/test_speed.py
> +
W391: blank line at end of file  <!-- Automatically posted by Lintly -->

2020-10-29 12:26 UTC, tankefugl commented on pysilcam/tests/test_speed.py
> +from pysilcam.config import PySilcamSettings
F401: 'pysilcam.config.PySilcamSettings' imported but unused  <!-- Automatically posted by Lintly -->

2020-10-29 12:26 UTC, tankefugl commented on pysilcam/tests/test_speed.py
> +from pysilcam.postprocess import count_images_in_stats
F401: 'pysilcam.postprocess.count_images_in_stats' imported but unused  <!-- Automatically posted by Lintly -->

2020-10-29 12:26 UTC, tankefugl commented on pysilcam/tests/test_speed.py
> +from pysilcam.silcreport import silcam_report
F401: 'pysilcam.silcreport.silcam_report' imported but unused  <!-- Automatically posted by Lintly -->

2020-10-29 12:26 UTC, tankefugl commented on pysilcam/tests/test_speed.py
> +import glob
F401: 'glob' imported but unused  <!-- Automatically posted by Lintly -->

2020-10-29 12:27 UTC, tankefugl requested changes
[Lintly](https://github.com/grantmcconnaughey/Lintly) has detected code quality issues in this pull request.



<!-- Automatically posted by Lintly -->

2020-10-29 12:27 UTC, tankefugl commented on pysilcam/tests/test_speed.py
> +
W391: blank line at end of file  <!-- Automatically posted by Lintly -->

2020-11-02 14:59 UTC, nepstad approved these changes

2020-11-02 15:27 UTC, nepstad submitted a review, later dismissed

2020-11-02 15:42 UTC, nepstad commented on pysilcam/tests/test_z_classify.py
> +        assert td < pd.to_timedelta(time_limit), 'Processing time too long.'
to_timedelta uses nanoseconds as default time unit, probably not was intended here (pass unit='seconds' or similar to be explicit).

2020-11-03 11:35 UTC, nepstad approved these changes

2020-11-03 12:05 UTC, WillRNaylor approved these changes
Looks good.

2020-11-03 12:05 UTC, merged