55 h5stats
SINTEF/PySilCam pull request #70
Opened 2020-11-05 20:15 UTC by emlynjdavies

addresses #50

2020-11-05 20:16 UTC, tankefugl requested changes
[Lintly](https://github.com/grantmcconnaughey/Lintly) has detected code quality issues in this pull request.



<!-- Automatically posted by Lintly -->

2020-11-05 20:16 UTC, tankefugl commented on pysilcam/tests/test_process.py
> +    assert len(matching_elements) == len(stats.columns.tolist()) == len(column_string), 'output STATS file contains unexpected columns'
E501: line too long (135 > 130 characters)  <!-- Automatically posted by Lintly -->

2020-11-05 20:16 UTC, tankefugl commented on pysilcam/silcamgui/silcamgui.py
> +                    filter = (('*-STATS.h5'))
E251: unexpected spaces around keyword / parameter equals  <!-- Automatically posted by Lintly -->

2020-11-05 20:16 UTC, tankefugl commented on pysilcam/silcamgui/silcamgui.py
> +                    filter = (('*-STATS.h5'))
E251: unexpected spaces around keyword / parameter equals  <!-- Automatically posted by Lintly -->

2020-11-05 20:16 UTC, tankefugl commented on pysilcam/silcamgui/silcamgui.py
> +                    filter = (('*-STATS.h5'))
E128: continuation line under-indented for visual indent  <!-- Automatically posted by Lintly -->

2020-11-05 20:16 UTC, tankefugl commented on pysilcam/silcamgui/silcamgui.py
> +                    caption = 'Load a *-STATS.h5 file',
E251: unexpected spaces around keyword / parameter equals  <!-- Automatically posted by Lintly -->

2020-11-05 20:16 UTC, tankefugl commented on pysilcam/silcamgui/silcamgui.py
> +                    caption = 'Load a *-STATS.h5 file',
E251: unexpected spaces around keyword / parameter equals  <!-- Automatically posted by Lintly -->

2020-11-05 20:16 UTC, tankefugl commented on pysilcam/silcamgui/silcamgui.py
> +                    caption = 'Load a *-STATS.h5 file',
E128: continuation line under-indented for visual indent  <!-- Automatically posted by Lintly -->

2020-11-05 20:16 UTC, tankefugl commented on pysilcam/silcamgui/silcamgui.py
> +            plt.savefig(self.stats_filename.replace('-STATS.h5','') +
E231: missing whitespace after ','  <!-- Automatically posted by Lintly -->

2020-11-05 20:16 UTC, tankefugl commented on pysilcam/silcamgui/silcamgui.py
> +            plt.savefig(self.stats_filename.replace('-STATS.h5','') + '-Summary_gas.png',
E231: missing whitespace after ','  <!-- Automatically posted by Lintly -->

2020-11-05 20:16 UTC, tankefugl commented on pysilcam/silcamgui/silcamgui.py
> +            plt.savefig(self.stats_filename.replace('-STATS.h5','') + '-Summary_oil.png',
E231: missing whitespace after ','  <!-- Automatically posted by Lintly -->

2020-11-05 20:16 UTC, tankefugl commented on pysilcam/silcamgui/silcamgui.py
> +            plt.savefig(self.stats_filename.replace('-STATS.h5','') + '-Summary.png',
E231: missing whitespace after ','  <!-- Automatically posted by Lintly -->

2020-11-05 20:16 UTC, tankefugl commented on pysilcam/silcamgui/interactive_summary.py
> +            outputname = self.stats_filename.replace('-STATS.h5','-PSD-' + timestring)
E231: missing whitespace after ','  <!-- Automatically posted by Lintly -->

2020-11-05 20:16 UTC, tankefugl commented on pysilcam/silcamgui/interactive_summary.py
> +        stats= pd.read_hdf(self.stats_filename, 'ParticleStats/stats')
E225: missing whitespace around operator  <!-- Automatically posted by Lintly -->

2020-11-05 20:16 UTC, tankefugl commented on pysilcam/silcamgui/guicalcs.py
> +    outfile = outfile.replace('-STATS.h5','')
E231: missing whitespace after ','  <!-- Automatically posted by Lintly -->

2020-11-05 20:16 UTC, tankefugl commented on pysilcam/postprocess.py
> +    outname = os.path.join(path, name.replace('-STATS.h5','')) + '-Start' + str(actual_start) + '-End' + str(
E231: missing whitespace after ','  <!-- Automatically posted by Lintly -->

2020-11-05 20:16 UTC, tankefugl commented on pysilcam/postprocess.py
> +    dfa.to_excel(stats_filename.replace('-STATS.h5','') +
E231: missing whitespace after ','  <!-- Automatically posted by Lintly -->

2020-11-05 20:16 UTC, tankefugl commented on pysilcam/postprocess.py
> +    df.to_excel(stats_filename.replace('-STATS.h5','') +
E231: missing whitespace after ','  <!-- Automatically posted by Lintly -->

2020-11-06 07:30 UTC, tankefugl requested changes
[Lintly](https://github.com/grantmcconnaughey/Lintly) has detected code quality issues in this pull request.



<!-- Automatically posted by Lintly -->

2020-11-06 07:30 UTC, tankefugl commented on pysilcam/silcamgui/silcamgui.py
> +            plt.savefig(self.stats_filename.replace('-STATS.h5','') +
E231: missing whitespace after ','  <!-- Automatically posted by Lintly -->

2020-11-06 07:30 UTC, tankefugl commented on pysilcam/silcamgui/silcamgui.py
> +            plt.savefig(self.stats_filename.replace('-STATS.h5','') + '-Summary_gas.png',
E231: missing whitespace after ','  <!-- Automatically posted by Lintly -->

2020-11-06 07:30 UTC, tankefugl commented on pysilcam/silcamgui/silcamgui.py
> +            plt.savefig(self.stats_filename.replace('-STATS.h5','') + '-Summary_oil.png',
E231: missing whitespace after ','  <!-- Automatically posted by Lintly -->

2020-11-06 07:30 UTC, tankefugl commented on pysilcam/silcamgui/silcamgui.py
> +            plt.savefig(self.stats_filename.replace('-STATS.h5','') + '-Summary.png',
E231: missing whitespace after ','  <!-- Automatically posted by Lintly -->

2020-11-06 07:30 UTC, tankefugl commented on pysilcam/silcamgui/interactive_summary.py
> +            outputname = self.stats_filename.replace('-STATS.h5','-PSD-' + timestring)
E231: missing whitespace after ','  <!-- Automatically posted by Lintly -->

2020-11-06 07:47 UTC, tankefugl submitted a review, later dismissed
[Lintly](https://github.com/grantmcconnaughey/Lintly) has detected code quality issues in this pull request.



<!-- Automatically posted by Lintly -->

2020-11-06 07:47 UTC, tankefugl commented on pysilcam/silcamgui/silcamgui.py
> +        if self.settings.ExportParticles.export_images == True:
E712: comparison to True should be 'if cond is True:' or 'if cond:'  <!-- Automatically posted by Lintly -->

2020-11-11 09:49 UTC, emlynjdavies commented
hangs on windows

2020-11-12 09:15 UTC, emlynjdavies commented
On windows:

Traceback (most recent call last):
  File "C:\Users\emlynd\Anaconda3\envs\silcam\Scripts\silcam-script.py", line 11, in <module>
    load_entry_point('PySilCam', 'console_scripts', 'silcam')()
  File "c:\users\emlynd\pysilcam\pysilcam\__main__.py", line 97, in silcam
    nbImages=nbImages, overwriteSTATS=overwriteSTATS)
  File "c:\users\emlynd\pysilcam\pysilcam\__main__.py", line 319, in silcam_process
    settings, rts=rts)
  File "c:\users\emlynd\pysilcam\pysilcam\__main__.py", line 581, in collector
    writeCSV(datafilename, task)
  File "c:\users\emlynd\pysilcam\pysilcam\__main__.py", line 623, in writeCSV
    with pd.HDFStore(datafilename + '-STATS.h5', 'a') as fh:
  File "C:\Users\emlynd\Anaconda3\envs\silcam\lib\site-packages\pandas\io\pytables.py", line 450, in __init__
    'importing'.format(ex=str(ex)))
ImportError: HDFStore requires PyTables, "DLL load failed: The specified module could not be found." problem importing

2020-12-08 20:29 UTC, nepstad submitted a review, later dismissed

2020-12-08 20:33 UTC, nepstad commented on pysilcam/silcamgui/silcamgui.py
>  DEFAULT_CONFIG = os.path.join(os.path.dirname(__file__), '../config_example.ini')
Avoid using / in path construction

2020-12-08 20:35 UTC, nepstad commented on pysilcam/tests/test_standards.py
> +    stats_file = os.path.join(ROOTPATH, 'STANDARDS/proc/StandardsBig-STATS.h5')
Avoid using / in path construction

2020-12-08 20:35 UTC, nepstad commented on pysilcam/tests/test_standards.py
> +    stats_file = os.path.join(ROOTPATH, 'STANDARDS/proc/StandardsSmall-STATS.h5')
Avoid using / in path construction

2020-12-08 20:35 UTC, nepstad commented on tfl_tools/investigate_particles.py
> +    stats_file = '/mnt/ARRAY/ENTICE/Data/proc/' + stn + '-STATS.h5'
Avoid using / in path construction

2020-12-08 20:35 UTC, nepstad commented on tfl_tools/silcam_classifier_database_builder.py
> +stats_file = '/mnt/ARRAY/ENTICE/Data/proc/STN10-STATS.h5'
Avoid using / in path construction

2020-12-08 20:35 UTC, nepstad commented on tfl_tools/silcam_self_learn.py
> +stats_file = '/mnt/nasdrive/Miljoteknologi/MK102013220_SILCAM_IPR_EJD/RUNDE_June2017/LowMag/proc/STN05-STATS.h5'
Avoid using / in path construction

2020-12-08 20:47 UTC, emlynjdavies commented
pysilcam\tests\test_standards.py:89:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

path_or_buf = 'C:\\Users\\emlynd\\Documents\\pysilcam-testdata\\pysilcam-testdata\\unittest-data\\STANDARDS\\proc\\StandardsSmall-STATS.h5'
key = 'ParticleStats', mode = 'stats', errors = 'strict', where = None, start = None
stop = None, columns = None, iterator = False, chunksize = None, kwargs = {}

    def read_hdf(
        path_or_buf,
        key=None,
        mode: str = "r",
        errors: str = "strict",
        where=None,
        start: Optional[int] = None,
        stop: Optional[int] = None,
        columns=None,
        iterator=False,
        chunksize: Optional[int] = None,
        **kwargs,
    ):
        """
        Read from the store, close it if we opened it.

        Retrieve pandas object stored in file, optionally based on where
        criteria.

        .. warning::

           Pandas uses PyTables for reading and writing HDF5 files, which allows
           serializing object-dtype data with pickle when using the "fixed" format.
           Loading pickled data received from untrusted sources can be unsafe.

           See: https://docs.python.org/3/library/pickle.html for more.

        Parameters
        ----------
        path_or_buf : str, path object, pandas.HDFStore or file-like object
            Any valid string path is acceptable. The string could be a URL. Valid
            URL schemes include http, ftp, s3, and file. For file URLs, a host is
            expected. A local file could be: ``file://localhost/path/to/table.h5``.

            If you want to pass in a path object, pandas accepts any
            ``os.PathLike``.

            Alternatively, pandas accepts an open :class:`pandas.HDFStore` object.

            By file-like object, we refer to objects with a ``read()`` method,
            such as a file handler (e.g. via builtin ``open`` function)
            or ``StringIO``.
        key : object, optional
            The group identifier in the store. Can be omitted if the HDF file
            contains a single pandas object.
        mode : {'r', 'r+', 'a'}, default 'r'
            Mode to use when opening the file. Ignored if path_or_buf is a
            :class:`pandas.HDFStore`. Default is 'r'.
        errors : str, default 'strict'
            Specifies how encoding and decoding errors are to be handled.
            See the errors argument for :func:`open` for a full list
            of options.
        where : list, optional
            A list of Term (or convertible) objects.
        start : int, optional
            Row number to start selection.
        stop  : int, optional
            Row number to stop selection.
        columns : list, optional
            A list of columns names to return.
        iterator : bool, optional
            Return an iterator object.
        chunksize : int, optional
            Number of rows to include in an iteration when using an iterator.
        **kwargs
            Additional keyword arguments passed to HDFStore.

        Returns
        -------
        item : object
            The selected object. Return type depends on the object stored.

        See Also
        --------
        DataFrame.to_hdf : Write a HDF file from a DataFrame.
        HDFStore : Low-level access to HDF files.

        Examples
        --------
        >>> df = pd.DataFrame([[1, 1.0, 'a']], columns=['x', 'y', 'z'])
        >>> df.to_hdf('./store.h5', 'data')
        >>> reread = pd.read_hdf('./store.h5')
        """
        if mode not in ["r", "r+", "a"]:
>           raise ValueError(
                f"mode {mode} is not allowed while performing a read. "
                f"Allowed modes are r, r+ and a."
            )
E           ValueError: mode stats is not allowed while performing a read. Allowed modes are r, r+ and a.

..\Anaconda3\envs\silcam\lib\site-packages\pandas\io\pytables.py:359: ValueError
------------------------------ Captured stdout call -------------------------------

2020-12-08 21:06 UTC, emlynjdavies commented on tfl_tools/silcam_self_learn.py
> +stats_file = '/mnt/nasdrive/Miljoteknologi/MK102013220_SILCAM_IPR_EJD/RUNDE_June2017/LowMag/proc/STN05-STATS.h5'
#79

2020-12-08 21:06 UTC, emlynjdavies commented on tfl_tools/silcam_classifier_database_builder.py
> +stats_file = '/mnt/ARRAY/ENTICE/Data/proc/STN10-STATS.h5'
refer to #79

2020-12-08 21:07 UTC, emlynjdavies commented on tfl_tools/investigate_particles.py
> +    stats_file = '/mnt/ARRAY/ENTICE/Data/proc/' + stn + '-STATS.h5'
refer to #78

2020-12-08 21:09 UTC, nepstad approved these changes

2020-12-09 10:30 UTC, WillRNaylor approved these changes
I just read the diff, and didn't test locally. Will test locally if you want me to, or you can just merge yourself.

Nice to see all the formatting tidying too.

2020-12-09 11:08 UTC, merged