81 interactive summary bug
SINTEF/PySilCam pull request #88
Opened 2020-12-15 13:55 UTC by emlynjdavies

* Updates interactive summary to work with the latest libraries.
* Begin to use xarray for handling processed data
* Users can still select old STATS.csv files, in which case they will be converted to HDF if the TIMSERIES.xls sheets don't already exist

2020-12-15 13:56 UTC, tankefugl requested changes
[Lintly](https://github.com/grantmcconnaughey/Lintly) has detected code quality issues in this pull request.



<!-- Automatically posted by Lintly -->

2020-12-15 13:56 UTC, tankefugl commented on pysilcam/silcamgui/interactive_summary.py
> +        #plt.sca(self.axisconstant)
E265: block comment should start with '# '  <!-- Automatically posted by Lintly -->

2020-12-15 13:56 UTC, tankefugl commented on pysilcam/silcamgui/interactive_summary.py
> +        #plt.sca(self.axistext)
E265: block comment should start with '# '  <!-- Automatically posted by Lintly -->

2020-12-15 13:56 UTC, tankefugl commented on pysilcam/silcamgui/interactive_summary.py
> +        self.axispsd.vlines(psd_peak_gas, 0, max(ds_psd['vd_gas']), 'b', linestyle=':', linewidth=1, label='Gas peak d50: {:0.0f}um'.format(psd_peak_gas))
E501: line too long (154 > 130 characters)  <!-- Automatically posted by Lintly -->

2020-12-15 13:56 UTC, tankefugl commented on pysilcam/silcamgui/interactive_summary.py
> +        self.axispsd.vlines(psd_peak_oil, 0, max(ds_psd['vd_oil']), color=[0.7, 0.4, 0], linestyle=':', linewidth=1, label='Oil peak: {:0.0f}um'.format(psd_peak_oil))
E501: line too long (166 > 130 characters)  <!-- Automatically posted by Lintly -->

2020-12-15 13:56 UTC, tankefugl commented on pysilcam/silcamgui/interactive_summary.py
> +        self.axispsd.vlines(psd_peak_total, 0, max(ds_psd['vd_total']), 'k', linestyle=':', linewidth=1, label='Total peak: {:0.0f}um'.format(psd_peak_total))
E501: line too long (158 > 130 characters)  <!-- Automatically posted by Lintly -->

2020-12-15 13:56 UTC, tankefugl commented on pysilcam/silcamgui/interactive_summary.py
> +        self.axispsd.vlines(psd_d50_gas, 0, max(ds_psd['vd_gas']), 'b', linestyle='--', linewidth=1, label='Gas d50: {:0.0f}um'.format(psd_d50_gas))
E501: line too long (148 > 130 characters)  <!-- Automatically posted by Lintly -->

2020-12-15 13:56 UTC, tankefugl commented on pysilcam/silcamgui/interactive_summary.py
> +        self.axispsd.vlines(psd_d50_oil, 0, max(ds_psd['vd_oil']), color=[0.7, 0.4, 0], linestyle='--', linewidth=1, label='Oil d50: {:0.0f}um'.format(psd_d50_oil))
E501: line too long (164 > 130 characters)  <!-- Automatically posted by Lintly -->

2020-12-15 13:56 UTC, tankefugl commented on pysilcam/silcamgui/interactive_summary.py
> +        self.axispsd.vlines(psd_d50_total, 0, max(ds_psd['vd_total']), 'k', linestyle='--', linewidth=1, label='Total d50: {:0.0f}um'.format(psd_d50_total))
E501: line too long (156 > 130 characters)  <!-- Automatically posted by Lintly -->

2020-12-15 13:56 UTC, tankefugl commented on pysilcam/silcamgui/interactive_summary.py
> +        #plt.sca(self.axispsd)
E265: block comment should start with '# '  <!-- Automatically posted by Lintly -->

2020-12-15 13:56 UTC, tankefugl commented on pysilcam/silcamgui/interactive_summary.py
> +            #plt.sca(self.axisconstant)
E265: block comment should start with '# '  <!-- Automatically posted by Lintly -->

2020-12-15 13:56 UTC, tankefugl commented on pysilcam/silcamgui/interactive_summary.py
> +            #plt.sca(self.axistext)
E265: block comment should start with '# '  <!-- Automatically posted by Lintly -->

2020-12-15 13:56 UTC, tankefugl commented on pysilcam/silcamgui/interactive_summary.py
> +            #plt.sca(self.axispsd)
E265: block comment should start with '# '  <!-- Automatically posted by Lintly -->

2020-12-15 13:56 UTC, tankefugl commented on pysilcam/silcamgui/interactive_summary.py
> +            psd = ds_slice.mean(dim='time')
F841: local variable 'psd' is assigned to but never used  <!-- Automatically posted by Lintly -->

2020-12-15 13:56 UTC, tankefugl commented on pysilcam/silcamgui/interactive_summary.py
> +        self.vd_oil = oil.iloc[:,1:53].to_numpy(dtype=float)
E231: missing whitespace after ','  <!-- Automatically posted by Lintly -->

2020-12-15 13:56 UTC, tankefugl commented on pysilcam/silcamgui/interactive_summary.py
> +        print('timeseriesgas_file',timeseriesgas_file)
E231: missing whitespace after ','  <!-- Automatically posted by Lintly -->

2020-12-15 13:56 UTC, tankefugl commented on pysilcam/silcamgui/interactive_summary.py
> +
W293: blank line contains whitespace  <!-- Automatically posted by Lintly -->

2020-12-15 13:56 UTC, tankefugl commented on pysilcam/silcamgui/interactive_summary.py
> +                                                QMessageBox.ActionRole)
E127: continuation line over-indented for visual indent  <!-- Automatically posted by Lintly -->

2020-12-15 13:56 UTC, tankefugl commented on pysilcam/silcamgui/interactive_summary.py
> +                        '\n\nWe will now load the STATS file ' +
E127: continuation line over-indented for visual indent  <!-- Automatically posted by Lintly -->

2020-12-15 13:56 UTC, tankefugl commented on pysilcam/silcamgui/interactive_summary.py
> +    def old_data_check(self):
E303: too many blank lines (2)  <!-- Automatically posted by Lintly -->

2020-12-15 13:56 UTC, tankefugl commented on pysilcam/silcamgui/interactive_summary.py
> +        #plt.axis('off')
E265: block comment should start with '# '  <!-- Automatically posted by Lintly -->

2020-12-15 13:56 UTC, tankefugl commented on pysilcam/silcamgui/interactive_summary.py
> +        #plt.sca(self.axistext)
E265: block comment should start with '# '  <!-- Automatically posted by Lintly -->

2020-12-15 13:56 UTC, tankefugl commented on pysilcam/postprocess.py
> +    for I in np.arange(1, 52, 1):
E741: ambiguous variable name 'I'  <!-- Automatically posted by Lintly -->

2020-12-15 13:56 UTC, tankefugl commented on pysilcam/postprocess.py
> +    for I in np.arange(1, 53, 1):
E741: ambiguous variable name 'I'  <!-- Automatically posted by Lintly -->

2020-12-15 14:26 UTC, tankefugl requested changes
[Lintly](https://github.com/grantmcconnaughey/Lintly) has detected code quality issues in this pull request.



<!-- Automatically posted by Lintly -->

2020-12-15 14:26 UTC, tankefugl commented on pysilcam/silcamgui/interactive_summary.py
> +            psd = ds_slice.mean(dim='time')
F841: local variable 'psd' is assigned to but never used  <!-- Automatically posted by Lintly -->

2020-12-15 14:26 UTC, tankefugl commented on pysilcam/silcamgui/interactive_summary.py
> +
W293: blank line contains whitespace  <!-- Automatically posted by Lintly -->

2020-12-15 14:26 UTC, tankefugl commented on pysilcam/silcamgui/interactive_summary.py
> +                          max(np.sum(self.vd_total,axis=1)))
E231: missing whitespace after ','  <!-- Automatically posted by Lintly -->

2020-12-15 14:26 UTC, tankefugl commented on pysilcam/silcamgui/interactive_summary.py
> +            self.axisconstant.set_ylim(min([min(np.sum(self.vd_total,axis=1)),
E231: missing whitespace after ','  <!-- Automatically posted by Lintly -->

2020-12-15 14:26 UTC, tankefugl commented on pysilcam/silcamgui/interactive_summary.py
> +            self.axisconstant.plot(self.u, np.sum(self.vd_total,axis=1),'k.', alpha=0.2)
E231: missing whitespace after ','  <!-- Automatically posted by Lintly -->

2020-12-15 14:26 UTC, tankefugl commented on pysilcam/silcamgui/interactive_summary.py
> +            self.axisconstant.plot(self.u, np.sum(self.vd_total,axis=1),'k.', alpha=0.2)
E231: missing whitespace after ','  <!-- Automatically posted by Lintly -->

2020-12-15 14:26 UTC, tankefugl commented on pysilcam/silcamgui/interactive_summary.py
> +        self.vd_gas = gas.iloc[:,1:53].to_numpy(dtype=float)
E231: missing whitespace after ','  <!-- Automatically posted by Lintly -->

2020-12-15 14:26 UTC, tankefugl commented on pysilcam/silcamgui/interactive_summary.py
> +        self.vd_oil = oil.iloc[:,1:53].to_numpy(dtype=float)
E231: missing whitespace after ','  <!-- Automatically posted by Lintly -->

2020-12-15 14:26 UTC, tankefugl commented on pysilcam/silcamgui/interactive_summary.py
> +
W293: blank line contains whitespace  <!-- Automatically posted by Lintly -->

2020-12-15 14:26 UTC, tankefugl commented on pysilcam/silcamgui/interactive_summary.py
> +        print('timeseriesgas_file',timeseriesgas_file)
E231: missing whitespace after ','  <!-- Automatically posted by Lintly -->

2020-12-15 14:26 UTC, tankefugl commented on pysilcam/silcamgui/interactive_summary.py
> +
W293: blank line contains whitespace  <!-- Automatically posted by Lintly -->

2020-12-15 14:26 UTC, tankefugl commented on pysilcam/silcamgui/interactive_summary.py
> +                                                QMessageBox.ActionRole)
E127: continuation line over-indented for visual indent  <!-- Automatically posted by Lintly -->

2020-12-15 14:26 UTC, tankefugl commented on pysilcam/silcamgui/interactive_summary.py
> +        load_stats_button = msgBox.addButton('OK',
F841: local variable 'load_stats_button' is assigned to but never used  <!-- Automatically posted by Lintly -->

2020-12-15 14:26 UTC, tankefugl commented on pysilcam/silcamgui/interactive_summary.py
> +                        '\n\nWe will now load the STATS file ' +
E127: continuation line over-indented for visual indent  <!-- Automatically posted by Lintly -->

2020-12-15 14:26 UTC, tankefugl commented on pysilcam/silcamgui/interactive_summary.py
> +        h5_file = self.stats_filename.replace('.csv','.h5')
E231: missing whitespace after ','  <!-- Automatically posted by Lintly -->

2020-12-15 14:26 UTC, tankefugl commented on pysilcam/silcamgui/interactive_summary.py
> +    def old_data_check(self):
E303: too many blank lines (2)  <!-- Automatically posted by Lintly -->

2020-12-15 14:26 UTC, tankefugl commented on pysilcam/postprocess.py
> +    for I in np.arange(1, 52, 1):
E741: ambiguous variable name 'I'  <!-- Automatically posted by Lintly -->

2020-12-15 14:26 UTC, tankefugl commented on pysilcam/postprocess.py
> +    for I in np.arange(1, 53, 1):
E741: ambiguous variable name 'I'  <!-- Automatically posted by Lintly -->

2020-12-15 14:37 UTC, tankefugl requested changes
[Lintly](https://github.com/grantmcconnaughey/Lintly) has detected code quality issues in this pull request.



<!-- Automatically posted by Lintly -->

2020-12-15 14:37 UTC, tankefugl commented on pysilcam/silcamgui/interactive_summary.py
> +            psd = ds_slice.mean(dim='time')
F841: local variable 'psd' is assigned to but never used  <!-- Automatically posted by Lintly -->

2020-12-15 14:37 UTC, tankefugl commented on pysilcam/silcamgui/interactive_summary.py
> +
W293: blank line contains whitespace  <!-- Automatically posted by Lintly -->

2020-12-15 14:37 UTC, tankefugl commented on pysilcam/silcamgui/interactive_summary.py
> +                          max(np.sum(self.vd_total,axis=1)))
E231: missing whitespace after ','  <!-- Automatically posted by Lintly -->

2020-12-15 14:37 UTC, tankefugl commented on pysilcam/silcamgui/interactive_summary.py
> +            self.axisconstant.set_ylim(min([min(np.sum(self.vd_total,axis=1)),
E231: missing whitespace after ','  <!-- Automatically posted by Lintly -->

2020-12-15 14:37 UTC, tankefugl commented on pysilcam/silcamgui/interactive_summary.py
> +            self.axisconstant.plot(self.u, np.sum(self.vd_total, axis=1),'k.', alpha=0.2)
E231: missing whitespace after ','  <!-- Automatically posted by Lintly -->

2020-12-15 14:37 UTC, tankefugl commented on pysilcam/silcamgui/interactive_summary.py
> +
W293: blank line contains whitespace  <!-- Automatically posted by Lintly -->

2020-12-15 14:37 UTC, tankefugl commented on pysilcam/silcamgui/interactive_summary.py
> +
W293: blank line contains whitespace  <!-- Automatically posted by Lintly -->

2020-12-15 14:37 UTC, tankefugl commented on pysilcam/silcamgui/interactive_summary.py
> +
W293: blank line contains whitespace  <!-- Automatically posted by Lintly -->

2020-12-15 14:37 UTC, tankefugl commented on pysilcam/silcamgui/interactive_summary.py
> +        load_stats_button = msgBox.addButton('OK', QMessageBox.ActionRole)
F841: local variable 'load_stats_button' is assigned to but never used  <!-- Automatically posted by Lintly -->

2020-12-15 14:37 UTC, tankefugl commented on pysilcam/postprocess.py
> +    for I in np.arange(1, 52, 1):
E741: ambiguous variable name 'I'  <!-- Automatically posted by Lintly -->

2020-12-15 14:37 UTC, tankefugl commented on pysilcam/postprocess.py
> +    for I in np.arange(1, 53, 1):
E741: ambiguous variable name 'I'  <!-- Automatically posted by Lintly -->

2020-12-16 13:12 UTC, tankefugl requested changes
[Lintly](https://github.com/grantmcconnaughey/Lintly) has detected code quality issues in this pull request.



<!-- Automatically posted by Lintly -->

2020-12-16 13:12 UTC, tankefugl commented on pysilcam/silcamgui/interactive_summary.py
> +            psd = ds_slice.mean(dim='time')
F841: local variable 'psd' is assigned to but never used  <!-- Automatically posted by Lintly -->

2020-12-16 13:12 UTC, tankefugl commented on pysilcam/silcamgui/interactive_summary.py
> +
W293: blank line contains whitespace  <!-- Automatically posted by Lintly -->

2020-12-16 13:12 UTC, tankefugl commented on pysilcam/silcamgui/interactive_summary.py
> +                          max(np.sum(self.vd_total,axis=1)))
E231: missing whitespace after ','  <!-- Automatically posted by Lintly -->

2020-12-16 13:12 UTC, tankefugl commented on pysilcam/silcamgui/interactive_summary.py
> +            self.axisconstant.set_ylim(min([min(np.sum(self.vd_total,axis=1)),
E231: missing whitespace after ','  <!-- Automatically posted by Lintly -->

2020-12-16 13:12 UTC, tankefugl commented on pysilcam/silcamgui/interactive_summary.py
> +            self.axisconstant.plot(self.u, np.sum(self.vd_total, axis=1),'k.', alpha=0.2)
E231: missing whitespace after ','  <!-- Automatically posted by Lintly -->

2020-12-16 13:12 UTC, tankefugl commented on pysilcam/silcamgui/interactive_summary.py
> +
W293: blank line contains whitespace  <!-- Automatically posted by Lintly -->

2020-12-16 13:12 UTC, tankefugl commented on pysilcam/silcamgui/interactive_summary.py
> +
W293: blank line contains whitespace  <!-- Automatically posted by Lintly -->

2020-12-16 13:12 UTC, tankefugl commented on pysilcam/silcamgui/interactive_summary.py
> +
W293: blank line contains whitespace  <!-- Automatically posted by Lintly -->

2020-12-16 13:12 UTC, tankefugl commented on pysilcam/silcamgui/interactive_summary.py
> +        load_stats_button = msgBox.addButton('OK', QMessageBox.ActionRole)
F841: local variable 'load_stats_button' is assigned to but never used  <!-- Automatically posted by Lintly -->

2020-12-16 13:22 UTC, tankefugl requested changes
[Lintly](https://github.com/grantmcconnaughey/Lintly) has detected code quality issues in this pull request.



<!-- Automatically posted by Lintly -->

2020-12-16 13:22 UTC, tankefugl commented on pysilcam/silcamgui/interactive_summary.py
> +
W293: blank line contains whitespace  <!-- Automatically posted by Lintly -->

2020-12-16 13:22 UTC, tankefugl commented on pysilcam/silcamgui/interactive_summary.py
> +
W293: blank line contains whitespace  <!-- Automatically posted by Lintly -->

2020-12-16 13:22 UTC, tankefugl commented on pysilcam/silcamgui/interactive_summary.py
> +
W293: blank line contains whitespace  <!-- Automatically posted by Lintly -->

2020-12-16 13:22 UTC, tankefugl commented on pysilcam/silcamgui/interactive_summary.py
> +
W293: blank line contains whitespace  <!-- Automatically posted by Lintly -->

2020-12-16 13:23 UTC, nepstad submitted a review, later dismissed

2020-12-16 13:33 UTC, nepstad approved these changes

2020-12-16 14:24 UTC, nepstad approved these changes

2020-12-16 14:51 UTC, WillRNaylor approved these changes

2020-12-16 14:54 UTC, merged